Repository studiometa/create-wordpress-project, pull requests merged in 2021-06, with the labels that each got.

#73 Fix Prettier configuration for Twig templates
  .github/workflows/tests.yml
  package-lock.json
  package.json
  template/.prettierrc.js
  template/package.json
  template/web/wp-content/themes/<%= slug %>/templates/components/header.twig
  template/web/wp-content/themes/<%= slug %>/templates/components/menu.twig
  template/web/wp-content/themes/<%= slug %>/templates/components/pagination.twig
  template/web/wp-content/themes/<%= slug %>/templates/pages/index.twig
  template/web/wp-content/themes/<%= slug %>/templates/pages/search.twig
Labels: bug

#74 Feature/composer 2
  .github/workflows/tests.yml
  template/composer.json
Labels: enhancement

#76 Update Readme & Node version
  template/.nvmrc
  template/readme.md
Labels: documentation, enhancement
